### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by thisismana** [Ernyoke/lambda-log-router#1]
Thank you so much for providing the well written blog post at https://ervinszilagyi.dev/articles/aws-lambda-extensions-with-rust.html and this corresponding repository.

Nevertheless, you should [add a license to your code](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

> For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

**Comment by Ernyoke** [comment]
Thank you for the feedback. I've added an MIT license to the project.
